env:
  es6: true
  node: true
  jest:  true
extends:
  - eslint:recommended
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
parser: babel-eslint
rules:
  "comma-dangle": ["error", "never"]
  "no-unused-expressions": "off"
  "no-unused-vars": "off"
